<?php
$lang=array(
    "cat0"=>"Categorii animale", //cat=>categorii.php
    "cat1"=>"Din dragoste pentru animale",
    "cat2"=>"Acasă",
    "cat3"=>"Despre noi",
    "cat4"=>"Cum pot ajuta?",
    "cat5"=>"Alătură-te voluntarilor",
    "cat6"=>"Donează",
    "cat7"=>"Adoptă",
    "cat8"=>"Contact",
    "cat9"=>"Română",
    "cat10"=>"Engleză",
    "cat11"=>"Categorii animale",
    "cat12"=>"Câini",
    "cat13"=>"Pisici",
    "cat14"=>"Hamsteri",
    "cat15"=>"Papagali",
    "pg_a1"=>"Cine suntem noi?", //pg_a=>pagina-acasa.php
    "pg_a2"=>"O asociație care salvează și pregătește spre adopție o mulțime de animăluțe fără stăpân.",
    "pg_a3"=>" Află mai multe",
    "pg_a4"=>"Cum ne găsești?",
    "pg_a5"=>"Dacă ai anumite întrebări, îți vom răspunde cu drag!",
    "pg_a6"=>"Click aici",
    "pg_a7"=>"Donează!",
    "pg_a8"=>"Ajută-ne să hrănim animăluțele!",
    "pg_a9"=>"Vreau să donez!",
    "pg_a10"=>"Adoptă!",
    "pg_a11"=>"Oferă unui suflet o viață mai bună!",
    "pg_a12"=>"Vreau să adopt!",
    "pg_a13"=>"Fii voluntar!",
    "pg_a14"=>"O plimbare cu un animăluț nu strică!",
    "pg_a15"=>"Vreau să devin voluntar!",
    "pg_a16"=>"uriașul blând",
    "pg_a17"=>"Robi este un iepure de talie mare, abandonat de familia sa care s-a mutat la oraș. Datorită unor persoane cu suflet mare, Robi a ajuns la noi, 
    iar după scurt timp și-a găsit o nouă familie care îl răsfață. Cu ajutorul nostru, acesta și-a găsit un cămin potrivit unde poate duce o viață liniștită și unde 
    are parte de iubire necondiționată.",
    "pg_a18"=>"bunicuța",
    "pg_a19"=>"Lola este un metiș care a fost loială stăpânului până la sfârșitul vieții acestuia. După acel moment tragic, Lola a fost adusă la adapostul nostru
    unde a avut parte de multă atenție și iubire. În prezent, este adoptată de o voluntară de-a noastră care are grijă ca ultimii ani de viață ai Lolei să fie cei mai buni.",
    "pg_d0"=>"Despre noi", //pg_a=>pagina-despre.php
    "pg_d1"=>"Adăpostul",
    "pg_d2"=>"a apărut în anul 1972 și este o organizație non-profit unde „oamenii ajută animalele și animalele ajută oamenii” prin dragostea pe care o primim înzecit înapoi de la prietenii noștri necuvântători.",
    "pg_d3"=>"Realizări",
    "pg_d4"=>"Dotarea/obținerea de echipamente necesare capturării câinilor (tub, pistol tranchilizant, cuști de transport, lese și zgărzi,);",
    "pg_d5"=>"Mașină autoutilitară pentru transportul animalelor, a hranei zilnice și a altor materiale necesare activității;",
    "pg_d6"=>"Sterilizarea a peste 1000 de câini și pisici în special din Județul Cluj;",
    "pg_d7"=>"Achiziționarea unui teren propriu.",
    "pg_d8"=>"În desfășurare",
    "pg_d9"=>"Programe de sterilizare a câinilor fără stăpâni - sterilizări la prețuri accesibile asociației și persoanelor care protejează câinii fără stăpân;",
    "pg_d10"=>"Promovarea și darea în adopție a sute de câini, sterilizați, deparazitați și vaccinați;",
    "pg_d11"=>"Intervenții punctuale în situații de urgență (animale accidentate, bolnave, abandonate, alte situații).",
    "pg_d12"=>"Echipa noastră",
    "pg_c0"=>"Date contact", //pg_a=>pagina-contact.php
    "pg_c1"=>"Calea Moților nr.1-3, Cluj, 400001",
    "pg_c2"=>"Telefon: 0761 617 716",
    "pg_c3"=>"Orar",
    "pg_c4"=>"Luni - Vineri: 8 am - 8 pm",
    "pg_c5"=>"Sâmbătă: 10 am - 4 pm",
    "pg_c6"=>"Duminică: 10 am - 2 pm",
    "pg_cf0"=>"Nume", //pt formular
    "pg_cf1"=>"Email",
    "pg_cf2"=>"Telefon",
    "pg_cf3"=>"Mesaj",
    "pg_cf4"=>"Trimite",
    "pg_d0"=>"Contul în lei:", //pg_a=>pagina-doneaza.php
    "pg_d1"=>"Contul în euro:", 
    "pg_d2"=>"Contul în dolari:", 
    "pg_d3"=>"PayPal procesează în siguranță", 
    "pg_d4"=>"donațiile.", 
    "pg_d5"=>"Vă puteți finaliza plata cu doar", 
    "pg_d6"=>"câteva click-uri.", 
    "pg_d7"=>"Vă mulțumim și contăm pe", 
    "pg_d8"=>"sprijinul dumneavoastră!",
    "pg_d9"=>"La locațiile:",
    "pg_d10"=>"str. Calatis, nr.5 (zona gării)",
    "pg_d11"=>"Minerva (în clădirea cu PETROM)",
    "pg_d12"=>"str. Pavlov, nr. 20",
    "pg_v0"=>"Voluntarii sunt esențiali pentru misiunea noastră.", //pg_a=>pagina-voluntari.php
    "pg_v1"=>"Crezi că te-ai descurca?",
    "pg_v2"=>"Iubești animalele și ai o pasiune de a-i ajuta pe alții? Întotdeauna avem nevoie de persoane care să plimbe câinii sau să stea cu pisicile, dar și de familii gazdă! ",
    "pg_v3"=>"Statutul de voluntar oferă, fiecăruia dintre voi, posibilitatea de a va implica activ în oricare dintre activitatile:",
    "pg_v4"=>"ajutor la întreținerea și îngrijirea   câinilor din adăpost - hranirea, asigurarea apei si curatarea tarcurilor",
    "pg_v5"=>"strângere de fonduri sau hrană pentru animalele din adăpost sau cele luate în grijă în diferite zone ale orașelor ",
    "pg_v6"=>"participarea activă la evenimente de strangere de fonduri si la colectele de mancare",
    "pg_v7"=>"participarea la eventimentele la care suntem invitati (Hiperparada animalelor, ZIOA etc.) sau la campaniile de sterilizare",
    "pg_v8"=>"promovare online și offline",
    "pg_v9"=>"informarea populatiei cu privire la redirectionarea a 2% din impozitul pe venit si colectarea formularelor",
    "pg_v10"=>"După ce procesăm cererea ta, te vom contacta pentru a discuta valabilitatea și interesele tale, precum și unde este nevoie de ajutorul tău. Vom programa o întâlnire unde îți vom povesti despre noi, vei cunoaște echipa și învăța lucrurile de bază. Împreună facem o diferență în viețile cățeilor și pisicilor din județul Cluj, dar și din împrejurimi!",
    "pg_v11"=>"Cerințe",
    "pg_v12"=>"Completați o cerere online.",
    "pg_v13"=>"Participați la întâlnirea generală a voluntarilor și tur al facilităților.",
    "pg_v14"=>"Să poți lucra independent și eficient astfel încât să termini cerințele voluntarilor.",
    "pg_v15"=>"Participarea la întâlniri de training adiționale.",
    "pg_v16"=>"Participarea la activitățile de voluntariat cel puțin o dată pe lună.",
    "pg_v17"=>"Tratarea cu atenție și grijă a animalelor.",
    "pg_v18"=>"Tratarea cu respect și profesionalism a clienților, angajaților și celorlalți voluntari.",
    "pg_v19"=>"Formular voluntari",
    "l_a0"=>"Detalii", // lista_animale.php
    "l_a1"=>"Adoptă/Foster",
    "l_a2"=>"Înapoi la categorii",
    "l_a0"=>"Detalii",
    "pg_l0"=>"Autentificare", // pagina-login.php
    "pg_l1"=>"Nume utilizator", 
    "pg_l2"=>"Parola", 
    "pg_l3"=>"Nu ai cont? Înregistrează-te!",
    "pg_l4"=>"Completează formularul:",
    "pg_l5"=>"Email",
    "pg_l6"=>"Telefon",
    "pg_l7"=>"Adresa",
    "pg_l8"=>"Oras",
    "pg_l9"=>"Tara",
    "pg_l10"=>"Creează cont",
    "q0"=>"Ce animăluț ți se potrivește?", //quiz.php
    "q1"=>"Ce activități preferi?",
    "q2"=>"Bicicleta de slăbit",
    "q3"=>"Înotul",
    "q4"=>"Dansul",
    "q5"=>"Care tip de personalitate te caracterizează cel mai bine?",
    "q6"=>"Introvertită",
    "q7"=>"Extrovertită",
    "q8"=>"Câte ore lipsești de acasă?",
    "q9"=>"Ce modalitate de relaxare preferi?",
    "q10"=>"O plimbare în parc",
    "q11"=>"Un film/o carte", 
    "q12"=>"Să ascult muzică",
    "q13"=>"Să stau pur și simplu",
    "q14"=>"Animalul tau de suflet este catelul!",
    "q15"=>"Animalul tau de suflet este pisica!",
    "q16"=>"Animalul tau de suflet este hamsterul!",
    "q17"=>"Animalul tau de suflet este chinchilla!",
    "q18"=>"Animalul tau de suflet este pestele!",
    "q19"=>"Află ce animal ți se potrivește",




);
?>